package poo;

public interface Trabajadores {
	
	public abstract double establece_bonus(double gratificacion);// PODEMOS OMITIR PUBLIC ABSTRACT YA QUE LA INTERFACE POR CONVENCION NO SUELEN PONERCE
	
	// LOS METODOS DE LAS INSTERFACES, SE DEFINEN Y NO SE DESARROLLAN.
	
	public static final double bonus_base=1500;
	
	// POR CONVENCION PODEMOS OMITIR EL PUBLIC STACTIC FINAL
	// ES PUBLICA PARA QUE SE PUEDA ACCEDER DESDE CUALQUIER CLASE A ELLA
	// STATICA POR QUE ES PERTENECIENTE A LA INTERFACE TRABAJADORES
	// FINAL POR QUE ES UNA CONSTANTE Y NO SE PUEDE REASIGNAR SU VALOR

}
